wip

diff --git a/centos-ci/jjb/rdgo.yml b/centos-ci/jjb/rdgo.yml
--- a/centos-ci/jjb/rdgo.yml
+++ b/centos-ci/jjb/rdgo.yml
@@ -41,16 +41,14 @@
           chmod a+x run-build
           scp -i ${WORKSPACE}/builder.key run-build builder@${node}:
           rsync -rv --progress -e "ssh -i ${WORKSPACE}/builder.key" continuous-atomic-overlay builder@${node}:
+          build_success=true
           if ! ssh -tt -i ${WORKSPACE}/builder.key builder@${node} ./run-build; then
-            rc="$?"
-          else
-            rc=0
+            build_success=false
           fi
           rsync -rv --progress -e "ssh -i ${WORKSPACE}/builder.key" builder@${node}:build-logs $WORKSPACE/build-logs || true
           # Exit with code from the build
-          if test $rc '!=' 0; then
-            echo 'Build failed'
-            echo $rc
+          if test "${build_success}" = "false"; then
+            echo 'Build failed, see logs above'; exit 1
           fi
             
     publishers:
diff --git a/centos-ci/run-build b/centos-ci/run-build
--- a/centos-ci/run-build
+++ b/centos-ci/run-build
@@ -13,9 +13,12 @@ rpmdistro-gitoverlay resolve --fetch-all --touch-if-changed fetch.stamp
 if ! test -f fetch.stamp; then
     exit 0
 fi
-rpmdistro-gitoverlay build --touch-if-changed build.stamp --logdir=build-logs
-if ! test -f build.stamp; then
-    exit 0
+build_success=false
+if rpmdistro-gitoverlay build --touch-if-changed build.stamp --logdir=build-logs; then
+    build_success=true
 fi
 cd ..
 rsync --progress -av --delete rdgo/ sig-atomic@artifacts.ci.centos.org::sig-atomic/rdgo/
+if test "${build_success}" = false; then
+    echo "Build failed, see logs above"; exit 1
+fi
